In [41]:
import numpy as np
import math
A = np.array([[1, 8, 17], 
    [2, 9, 38],
    [3,10,29]])
print(A)

[[ 1  8 17]
 [ 2  9 38]
 [ 3 10 29]]


In [94]:
def p_svd(A):
    n = A.shape[1]
    
    # Valores singulares de A
    AtA = np.matmul(A.transpose(),A)
    sv = map(math.sqrt,map(abs, np.linalg.eig(AtA)[0]))
    
    # Calculo de S
    S = np.eye(n)*np.tile(sv,(n,1))
    
    # Eigenvectores y V
    V = np.linalg.eig(AtA)[1]
    
    # Calculo de U
    U = np.matmul(A,np.matmul(V,np.linalg.inv(S)))
    
    svd = [U,S,V]
    
    return svd


In [95]:
p_svd(A)

[array([[ 0.35057526, -0.61648014, -0.70501718],
        [ 0.73534538, -0.28498942,  0.61485624],
        [ 0.5799691 ,  0.73398451, -0.35341559]]),
 array([[53.07660069,  0.        ,  0.        ],
        [ 0.        ,  1.02782934,  0.        ],
        [ 0.        ,  0.        ,  3.84941898]]),
 array([[ 0.06709498,  0.9879992 , -0.13912527],
        [ 0.28680061, -0.15265252, -0.94574976],
        [ 0.95563784, -0.02355385,  0.29360099]])]

In [84]:
np.matmul(svd[0],np.matmul(svd[1],svd[2].transpose()))


array([[ 1.,  8., 17.],
       [ 2.,  9., 38.],
       [ 3., 10., 29.]])