In [1]:
import numpy as np
import math
A = np.array([[1, 8, 17], 
    [2, 9, 38],
    [3,10,29]])
print(A)

[[ 1  8 17]
 [ 2  9 38]
 [ 3 10 29]]


In [2]:
def p_svd(A):
    n = A.shape[1]
    
    # Valores singulares de A
    AtA = np.matmul(A.transpose(),A)
    sv = map(math.sqrt,map(abs, np.linalg.eig(AtA)[0]))
    
    # Calculo de S
    S = np.eye(n)*np.tile(sv,(n,1))
    
    # Eigenvectores y V
    V = np.linalg.eig(AtA)[1]
    
    # Calculo de U
    U = np.matmul(A,np.matmul(V,np.linalg.inv(S)))
    
    svd = [U,S,V]
    
    return svd


In [3]:
Asvd = p_svd(A)

In [4]:
# Prueba SVD
np.matmul(Asvd[0],np.matmul(Asvd[1],Asvd[2].transpose()))

array([[ 1.,  8., 17.],
       [ 2.,  9., 38.],
       [ 3., 10., 29.]])

In [5]:
# Prueba minimos cuadrados
A = np.array([[1,1,1], 
    [0,2,5],
    [2,5,-1]])
x = np.array([5,3,-2])
print(x)
b = np.matmul(A,x)

[ 5  3 -2]


In [6]:
def p_mc(A,b):
    A_svd = p_svd(A)
    x = np.matmul(A_svd[2],np.matmul(np.linalg.inv(A_svd[1]),np.matmul(A_svd[0].transpose(),b)))
    return x

p_mc(A,b)

array([ 5.,  3., -2.])